import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { Innovation } from '../model/innovation.model';
import { User } from '../../users/model/user.model';
import {
  InnovationStatus,
  Visibility,
  PricingModel,
  Difficulty,
} from '../interfaces/innovation.interface';
import { ROLES } from '../../../shared/constants';

dotenv.config();

const sampleInnovations = [
  {
    title: 'Nova AI Desk Assistant',
    shortDescription: 'An autonomous desktop AI companion with motorized gimbal tracking and local voice processing.',
    description: 'Nova AI Desk Assistant combines advanced computer vision with local LLMs running on specialized edge hardware. It features a silent 3-axis gimbal that tracks user movement, responds to voice prompts instantly, and controls smart desk lighting and ergonomics.',
    category: 'AI & ML',
    subcategory: 'Hardware Assistants',
    tags: ['AI', 'Robotics', 'Desk', 'Automation', 'Voice'],
    coverImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800',
    ],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 299,
    currency: 'USD',
    technologyStack: ['Python', 'PyTorch', 'ESP32', 'C++'],
    difficulty: Difficulty.ADVANCED,
    featured: true,
    verified: true,
    likes: 142,
    bookmarks: 45,
    views: 1250,
    publishedAt: new Date(),
  },
  {
    title: 'EchoBeat ANC Headphones',
    shortDescription: 'Modular audiophile headphones with zero-latency lossless wireless audio and open-source DSP.',
    description: 'EchoBeat ANC represents the next evolution in modular headphones. Every driver, ear pad, and battery module can be replaced by the user in seconds without tools. Featuring custom planar magnetic drivers and open-source DSP firmware.',
    category: 'Wearables',
    subcategory: 'Audio',
    tags: ['Audio', 'Headphones', 'Modular', 'OpenSource', 'Hardware'],
    coverImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
    galleryImages: [
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
    ],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 349,
    currency: 'USD',
    technologyStack: ['C', 'ARM Cortex', 'DSP', 'Bluetooth 5.4'],
    difficulty: Difficulty.INTERMEDIATE,
    featured: true,
    verified: true,
    likes: 310,
    bookmarks: 89,
    views: 3400,
    publishedAt: new Date(),
  },
  {
    title: 'SolarEdge Smart Microgrid Inverter',
    shortDescription: 'Next-gen bidirectional inverter for home solar storage with AI load prediction.',
    description: 'SolarEdge Smart Inverter integrates silicon-carbide power electronics with predictive machine learning models to maximize solar self-consumption and battery lifespan during grid outages.',
    category: 'CleanTech',
    subcategory: 'Energy Storage',
    tags: ['Solar', 'CleanTech', 'Inverter', 'Energy', 'Battery'],
    coverImage: 'https://images.unsplash.com/photo-1509391365360-fa0ba1f3a2d2?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 1199,
    currency: 'USD',
    technologyStack: ['SiC Mosfets', 'C++', 'FreeRTOS'],
    difficulty: Difficulty.ADVANCED,
    featured: true,
    verified: true,
    likes: 88,
    bookmarks: 32,
    views: 890,
    publishedAt: new Date(),
  },
  {
    title: 'AeroDrone X1 Pro',
    shortDescription: 'Ultra-light carbon fiber autonomous drone for agricultural crop health scanning.',
    description: 'AeroDrone X1 Pro is engineered for precision agriculture. Capable of 45-minute continuous flight times and equipped with multispectral imaging sensors to detect crop water stress and nutrient deficiencies.',
    category: 'Drones',
    subcategory: 'Agriculture',
    tags: ['Drone', 'Agriculture', 'Autonomous', 'CarbonFiber'],
    coverImage: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 1850,
    currency: 'USD',
    technologyStack: ['PX4', 'ROS2', 'Python', 'C++'],
    difficulty: Difficulty.ADVANCED,
    featured: false,
    verified: true,
    likes: 67,
    bookmarks: 18,
    views: 540,
    publishedAt: new Date(),
  },
  {
    title: 'BioGrow Hydroponic Tower',
    shortDescription: 'Automated indoor vertical farming tower with hydroponic nutrient dosing and IoT sensors.',
    description: 'BioGrow allows urban families and restaurants to grow up to 48 varieties of leafy greens and herbs in less than 2 square feet. Fully controlled via WiFi with automated pH and EC nutrient balancing.',
    category: 'IoT',
    subcategory: 'Smart Home',
    tags: ['Hydroponics', 'IoT', 'Agriculture', 'SmartHome'],
    coverImage: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.FREE,
    price: 0,
    currency: 'USD',
    technologyStack: ['ESP32', 'Arduino', 'React Native'],
    difficulty: Difficulty.BEGINNER,
    featured: false,
    verified: false,
    likes: 45,
    bookmarks: 20,
    views: 410,
    publishedAt: new Date(),
  },
  {
    title: 'HapticVR Tactical Glove',
    shortDescription: 'Force-feedback haptic glove for immersive VR surgical and industrial training.',
    description: 'HapticVR uses micro-pneumatic actuators across each fingertip to provide realistic touch, texture, and resistance sensations for virtual reality simulations.',
    category: 'AR/VR',
    subcategory: 'Haptics',
    tags: ['VR', 'Haptics', 'AR', 'Simulation', 'Wearables'],
    coverImage: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.UNDER_REVIEW,
    pricingModel: PricingModel.LICENSE,
    price: 899,
    currency: 'USD',
    technologyStack: ['C++', 'Unreal Engine', 'Unity SDK', 'ARM'],
    difficulty: Difficulty.ADVANCED,
    featured: false,
    verified: false,
    likes: 12,
    bookmarks: 4,
    views: 105,
  },
  {
    title: 'QuantumKey Hardware Security Module',
    shortDescription: 'Open-source USB-C hardware authenticator with post-quantum encryption algorithms.',
    description: 'QuantumKey protects developer cryptographic identities using lattice-based post-quantum cryptography inside an ultra-durable titanium casing with fingerprint biometric verification.',
    category: 'IoT',
    subcategory: 'Security',
    tags: ['Security', 'Hardware', 'USB', 'Cryptography', 'Biometrics'],
    coverImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.DRAFT,
    pricingModel: PricingModel.PAID,
    price: 89,
    currency: 'USD',
    technologyStack: ['Rust', 'Embedded C', 'SecureElement'],
    difficulty: Difficulty.ADVANCED,
    featured: false,
    verified: false,
    likes: 5,
    bookmarks: 1,
    views: 40,
  },
  {
    title: 'ExoStep Robotic Ankle Assist',
    shortDescription: 'Lightweight exoskeleton ankle brace for mobility rehabilitation.',
    description: 'ExoStep provides intelligent gait assistance using lightweight carbon fiber struts and brushless DC actuators to help patients recovering from lower limb injuries walk naturally.',
    category: 'Robotics',
    subcategory: 'Medical & Rehab',
    tags: ['Robotics', 'Rehab', 'Exoskeleton', 'Medical', 'Hardware'],
    coverImage: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.LICENSE,
    price: 2499,
    currency: 'USD',
    technologyStack: ['C++', 'CAN Bus', 'ROS2', 'Embedded Linux'],
    difficulty: Difficulty.ADVANCED,
    featured: true,
    verified: true,
    likes: 198,
    bookmarks: 64,
    views: 1890,
    publishedAt: new Date(),
  },
  {
    title: 'LumiDesk Ergonomic OLED Lamp',
    shortDescription: 'Adaptive circadian desk lamp with ultra-thin organic LED lighting panel.',
    description: 'LumiDesk automatically adjusts color temperature and illuminance throughout the work day to match natural outdoor lighting cycles and reduce eye fatigue.',
    category: 'IoT',
    subcategory: 'Smart Lighting',
    tags: ['Lighting', 'OLED', 'Ergonomics', 'SmartDesk'],
    coverImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.ARCHIVED,
    pricingModel: PricingModel.PAID,
    price: 149,
    currency: 'USD',
    technologyStack: ['ESP8266', 'C++', 'MQTT'],
    difficulty: Difficulty.BEGINNER,
    featured: false,
    verified: false,
    likes: 30,
    bookmarks: 10,
    views: 310,
  },
  {
    title: 'MicroSensor Pro Water Analyzer',
    shortDescription: 'Handheld electrochemical water quality sensor for heavy metal detection.',
    description: 'MicroSensor Pro uses disposable lab-on-a-chip test strips to detect lead, arsenic, and mercury in drinking water in under 60 seconds with laboratory precision.',
    category: 'Biotech',
    subcategory: 'Environmental',
    tags: ['Water', 'Biotech', 'Sensors', 'Environment'],
    coverImage: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 199,
    currency: 'USD',
    technologyStack: ['STM32', 'C', 'Python'],
    difficulty: Difficulty.INTERMEDIATE,
    featured: false,
    verified: true,
    likes: 74,
    bookmarks: 23,
    views: 670,
    publishedAt: new Date(),
  },
  {
    title: 'TerraRover Mars Explorer Prototype',
    shortDescription: 'Open-source 6-wheel rocker-bogie educational rover platform.',
    description: 'TerraRover brings planetary rover mechanics to universities and robotics enthusiasts. Features machined aluminum suspension links, LiDAR navigation, and modular camera gimbals.',
    category: 'Robotics',
    subcategory: 'Education',
    tags: ['Robotics', 'Rover', 'Space', 'Education', 'ROS'],
    coverImage: 'https://images.unsplash.com/photo-1617791160505-6f00b046a874?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.FREE,
    price: 0,
    currency: 'USD',
    technologyStack: ['ROS2', 'Python', 'Raspberry Pi 5', 'C++'],
    difficulty: Difficulty.INTERMEDIATE,
    featured: true,
    verified: true,
    likes: 412,
    bookmarks: 130,
    views: 4500,
    publishedAt: new Date(),
  },
  {
    title: 'CryoCell Portable Biocooler',
    shortDescription: 'Battery-powered active cooling container for temperature-sensitive medicine transport.',
    description: 'CryoCell maintains temperatures between 2°C and 8°C for up to 72 hours using thermoelectric Peltier arrays and vacuum insulation for remote medical clinics.',
    category: 'Biotech',
    subcategory: 'Healthcare Logistics',
    tags: ['Healthcare', 'Cooler', 'Biotech', 'Battery'],
    coverImage: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 499,
    currency: 'USD',
    technologyStack: ['ARM Cortex M4', 'C', 'IoT Cellular'],
    difficulty: Difficulty.ADVANCED,
    featured: false,
    verified: true,
    likes: 95,
    bookmarks: 38,
    views: 780,
    publishedAt: new Date(),
  },
  {
    title: 'VeloPower Regenerative Bike Hub',
    shortDescription: 'Smart electric bike conversion hub with kinetic energy recovery and theft tracking.',
    description: 'VeloPower replaces standard rear bicycle wheels in 10 minutes to add 250W electric assist, regenerative downhill braking, and GPS/Cellular antitheft alerts.',
    category: 'CleanTech',
    subcategory: 'e-Mobility',
    tags: ['eBike', 'Mobility', 'CleanTech', 'Cycling'],
    coverImage: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 399,
    currency: 'USD',
    technologyStack: ['C++', 'BLE', 'GPS', 'MotorControl'],
    difficulty: Difficulty.INTERMEDIATE,
    featured: false,
    verified: false,
    likes: 110,
    bookmarks: 29,
    views: 920,
    publishedAt: new Date(),
  },
  {
    title: 'AcousticShield Smart Earplugs',
    shortDescription: 'Active industrial earplugs that block heavy machinery noise while allowing human speech.',
    description: 'AcousticShield uses real-time spectral filtering with ultra-low latency DSP chips to attenuate damaging industrial decibels without isolating workers from speech commands.',
    category: 'Wearables',
    subcategory: 'Safety',
    tags: ['Audio', 'Safety', 'Wearables', 'Industrial'],
    coverImage: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 179,
    currency: 'USD',
    technologyStack: ['DSP', 'Embedded C', 'Bluetooth'],
    difficulty: Difficulty.INTERMEDIATE,
    featured: false,
    verified: true,
    likes: 56,
    bookmarks: 14,
    views: 530,
    publishedAt: new Date(),
  },
  {
    title: 'OptiScanner 3D Desktop Laser',
    shortDescription: 'High-resolution structured-light 3D scanner for reverse engineering physical parts.',
    description: 'OptiScanner achieves 0.02mm metrology accuracy using dual industrial cameras and blue structured laser projection on a motorized calibrated turntable.',
    category: 'Robotics',
    subcategory: '3D Scanning',
    tags: ['3DScanning', 'Metrology', 'Laser', 'Hardware', 'CAD'],
    coverImage: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 899,
    currency: 'USD',
    technologyStack: ['C++', 'OpenCV', 'CUDA', 'Python'],
    difficulty: Difficulty.ADVANCED,
    featured: true,
    verified: true,
    likes: 245,
    bookmarks: 78,
    views: 2100,
    publishedAt: new Date(),
  },
  {
    title: 'AquaFlow Smart Tap Monitor',
    shortDescription: 'Screw-on tap sensor for real-time household water consumption monitoring.',
    description: 'AquaFlow attaches to standard faucets to measure water volume and temperature, sending alerts for leaks or abnormal water usage patterns directly to user smartphones.',
    category: 'IoT',
    subcategory: 'Smart Home',
    tags: ['Water', 'IoT', 'SmartHome', 'Conservation'],
    coverImage: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.FREE,
    price: 0,
    currency: 'USD',
    technologyStack: ['ESP32', 'BLE', 'React Native'],
    difficulty: Difficulty.BEGINNER,
    featured: false,
    verified: true,
    likes: 80,
    bookmarks: 22,
    views: 600,
    publishedAt: new Date(),
  },
  {
    title: 'NeuroSense EEG Headband',
    shortDescription: '8-channel dry-electrode EEG wearable for sleep staging and focus training.',
    description: 'NeuroSense provides research-grade brainwave recordings without messy conductive gel. Pairs with an AI sleep coaching application for insomnia therapy.',
    category: 'Wearables',
    subcategory: 'Neurotech',
    tags: ['EEG', 'Neurotech', 'Sleep', 'Wearables', 'AI'],
    coverImage: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.UNDER_REVIEW,
    pricingModel: PricingModel.PAID,
    price: 399,
    currency: 'USD',
    technologyStack: ['Python', 'SignalProcessing', 'BLE 5.2'],
    difficulty: Difficulty.ADVANCED,
    featured: false,
    verified: false,
    likes: 29,
    bookmarks: 9,
    views: 210,
  },
  {
    title: 'OmniArm 5-Axis Desktop Robot',
    shortDescription: 'High-speed desktop robotic arm for PCB assembly and pick-and-place automation.',
    description: 'OmniArm delivers repeatable sub-millimeter precision for lab electronics manufacturing and automated camera motion control.',
    category: 'Robotics',
    subcategory: 'Industrial Automation',
    tags: ['Robotics', 'Automation', 'PCB', 'Manufacturing'],
    coverImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 1450,
    currency: 'USD',
    technologyStack: ['C++', 'ROS2', 'CANopen', 'Python'],
    difficulty: Difficulty.ADVANCED,
    featured: true,
    verified: true,
    likes: 389,
    bookmarks: 112,
    views: 3900,
    publishedAt: new Date(),
  },
  {
    title: 'PureAir HEPA Nano-Filter Unit',
    shortDescription: 'Smart electrostatic air filtration system with formaldehyde and VOC sensors.',
    description: 'PureAir combines multi-stage medical HEPA filters with real-time laser particle counters and silent brushless DC fans.',
    category: 'CleanTech',
    subcategory: 'Air Quality',
    tags: ['AirQuality', 'CleanTech', 'HEPA', 'Sensors'],
    coverImage: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 249,
    currency: 'USD',
    technologyStack: ['ESP32', 'FreeRTOS', 'MQTT'],
    difficulty: Difficulty.BEGINNER,
    featured: false,
    verified: true,
    likes: 64,
    bookmarks: 21,
    views: 520,
    publishedAt: new Date(),
  },
  {
    title: 'HydroSense Soil Moisture Node',
    shortDescription: 'Solar-powered wireless soil sensor for vineyard and orchard irrigation management.',
    description: 'HydroSense transmits root-zone moisture and temperature telemetry over LoRaWAN up to 5 miles, eliminating over-watering in agriculture.',
    category: 'IoT',
    subcategory: 'Agriculture',
    tags: ['LoRaWAN', 'Agriculture', 'IoT', 'Sensors', 'Solar'],
    coverImage: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=800',
    galleryImages: [],
    visibility: Visibility.PUBLIC,
    status: InnovationStatus.PUBLISHED,
    pricingModel: PricingModel.PAID,
    price: 79,
    currency: 'USD',
    technologyStack: ['STM32WL', 'LoRaWAN', 'Embedded C'],
    difficulty: Difficulty.INTERMEDIATE,
    featured: false,
    verified: true,
    likes: 52,
    bookmarks: 16,
    views: 480,
    publishedAt: new Date(),
  },
];

async function runSeed() {
  const uri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/innomine';
  console.log(`Connecting to MongoDB at ${uri}...`);
  await mongoose.connect(uri);

  console.log('Finding or creating seed users...');
  let users = await User.find({ role: { $in: [ROLES.INNOVATOR, ROLES.ADMIN] } }).exec();

  if (users.length === 0) {
    console.log('No innovator/admin users found. Creating 3 default seed innovators...');
    const createdUsers = await User.create([
      {
        name: 'Dr. Elena Vance',
        email: 'elena.vance@innomine.io',
        password: 'Password123!',
        role: ROLES.INNOVATOR,
        isEmailVerified: true,
        isActive: true,
      },
      {
        name: 'Marcus Thorne',
        email: 'marcus.thorne@innomine.io',
        password: 'Password123!',
        role: ROLES.INNOVATOR,
        isEmailVerified: true,
        isActive: true,
      },
      {
        name: 'Sophia Chen',
        email: 'sophia.chen@innomine.io',
        password: 'Password123!',
        role: ROLES.INNOVATOR,
        isEmailVerified: true,
        isActive: true,
      },
    ]);
    users = createdUsers;
  }

  console.log('Clearing existing innovations...');
  await Innovation.deleteMany({});

  console.log(`Seeding ${sampleInnovations.length} realistic innovations...`);
  const innovationsToInsert = sampleInnovations.map((item, idx) => {
    const owner = users[idx % users.length];
    return {
      ...item,
      owner: owner._id,
    };
  });

  const inserted = await Innovation.create(innovationsToInsert);
  console.log(`Successfully inserted ${inserted.length} innovations.`);

  await mongoose.disconnect();
  console.log('Seed completed successfully!');
}

runSeed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
